name: Node Continuous Integration

on:
  push:
    paths:
      - .github/workflows/**/*
      - ./Makefile
      - ./.gitignore
      - ./js/**/*
      - ./tests/js/**/*
      - ./index.html
      - ./.eslintrc.json
      - ./package*.json
  pull_request:
    branches: [master]

jobs:
  app:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Setup Node 12
          uses: actions/setup-node@v1
          with:
            node-version: '12.x'
        - run: make start

  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node 12
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm/
            ./node_modules/
          key: ${{ github.ref }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ github.ref }}-node-
            ${{ github.ref }}-
      - name: Install Modules
        run: make install

  lint:
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node 12
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm/
            ./node_modules/
          key: ${{ github.ref }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ github.ref }}-node-
            ${{ github.ref }}-
      - name: Getting node_modules from cache
        run: make install
      - name: Checking JS linting
        run: npx eslint ./js/node ./tests/js  # This should be changed once JS is unified

  tests:
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node 12
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm/
            ./node_modules/
          key: ${{ github.ref }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ github.ref }}-node-
            ${{ github.ref }}-
      - name: Getting node_modules from cache
        run: make install
      - name: Running JS tests
        run: make tests
