name: Python Continuous Integration

on:
  push:
    paths:
      - .github/workflows/**/*
      - ./Makefile
      - ./.gitignore
      - ./pyc/**/*
      - ./tests/py/**/*
      - ./isort.cfg
      - ./app.py
      - ./requirements.txt
  pull_request:
    branches: [master]

jobs:
  app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - run: make start RT=py

  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Cache python libraries
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip/
            ./.venv/
          key: ${{ github.ref }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ github.ref }}-pip-
            ${{ github.ref }}-
      - name: Install Dependencies
        run: make install RT=py

  lint:
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Cache python libraries
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip/
            ./.venv/
          key: ${{ github.ref }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ github.ref }}-pip-
            ${{ github.ref }}-
      - name: Getting virtual environment from cache
        run: make install RT=py
      - name: Checking python linting
        run: make lint RT=py

  tests:
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Cache python libraries
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip/
            ./.venv/
          key: ${{ github.ref }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ github.ref }}-pip-
            ${{ github.ref }}-
      - name: Getting virtual environment from cache
        run: make install RT=py
      - name: Running python tests
        run: make tests RT=py
